### ISSUE TITLE
Future of VOConfigTask

### ISSUE THREAD

**Issue by jrha** [quattor/scdb-ant-utils#19]
The functionality provided by VOConfigTask is more generally useful than for just SCDB sites. Ideally it (or an equivalent) should be run during the release cycle to update the VO information we provide in the template-library.

We should decide what to do about it and how we maintain it in future.

**Comment by jouvin** [comment]
@jrha Clearly we need to maintain a tool for doing this outside SCDB. As the current implementation is a ant task, it may be an overkill to maintain it and may be easier to rewrite a tool in Python for example, easier to maintain than this Java Ant task.

As for running it as part of the release, it may be a good idea but this is also a little bit risky because one thing generated is the pool accounts per VO role whose names change if the list is updated... and this tend to happen! So a site may want to ensure that these particular templates are not updated unless he really ask for the upgrade.... This is the reason we rarely updated them in the grid templates.

**Comment by jouvin** [comment]
As discussed at the workshop, the current implementation is difficult to use inside Aquilon as it requires to install SCDB to get the templates generated. Before we manage to get the time to rewrite the tool independly of SCDB, it would be an improvement to ship a new version of the `quattor.build.xml` just to run `VOConfigTask` with default paths appropriate for Aquilon.

**Comment by jrha** [comment]
Resolved by https://github.com/quattor/tools/pull/18
